"""
Django settings for blog_home project.

Generated by 'django-admin startproject' using Django 5.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-@$@0n1xs9^)4b@f+zz_ak4b9n*s9_#m3w2um^!2)cdi2^kd*n*'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'haystack',
    'blog.apps.BlogConfig',
    'pure_pagination',
]

MIDDLEWARE = [
    'blog.forbidden_middleware.ForbiddenMiddleware',
    'blog.forbidden_middleware.SetTimestampCookieMiddleware',
    'blog.forbidden_middleware.TimestampCookieValidationMiddleware',
    'blog.forbidden_middleware.CookieEncryptionMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'blog.disable_cache_middleware.DisableCacheMiddleware',
]

ROOT_URLCONF = 'blog_home.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'blog_home.wsgi.application'

# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'blog',
        "USER": "root",
        "PASSWORD": "asxe666",
        "HOST": "127.0.0.1",
        "PORT": "3306",
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_TZ = False

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "blog/templates/sim", STATIC_URL),
    os.path.join(BASE_DIR, "blog/templates/argon", STATIC_URL),
    os.path.join(BASE_DIR, "blog/templates/home", STATIC_URL)
]

MEDIA_URL = 'media/'
MEDIA_ROOT = [
    os.path.join(BASE_DIR, MEDIA_URL),
    os.path.join(BASE_DIR, 'geoip/')
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# pure-pagination
PAGINATION_SETTINGS = {
    'PAGE_RANGE_DISPLAYED': 6,
    'MARGIN_PAGES_DISPLAYED': 2,
    'SHOW_FIRST_PAGE_WHEN_INVALID': True,
}

# haystack
HAYSTACK_CONNECTIONS = {
    'default': {
        'ENGINE': 'blog.whoosh_backend_cn.WhooshEngine',
        'PATH': os.path.join(BASE_DIR, 'whoosh_index'),
    },
}
HAYSTACK_SEARCH_RESULTS_PER_PAGE = 10
HAYSTACK_SIGNAL_PROCESSOR = 'haystack.signals.RealtimeSignalProcessor'

# ForbiddenMiddleware
OPEN_FORBIDDEN = True  # 是否启用屏蔽功能
MIN_FORBIDDEN_TIME = 60  # 最小屏蔽时长
MAX_FORBIDDEN_TIME = 600  # 最大屏蔽时长
FORBIDDEN_IP_SECONDS = 60  # 记录同一IP下用户被屏蔽次数的KEY的过期时间
FORBIDDEN_USER_SECONDS = 1  # 记录同一用户指定时间步长内访问次数的KEY的过期时间
FORBIDDEN_IP_COUNT = 5  # 同一IP的用户被屏蔽次数超过该值将屏蔽该IP
FORBIDDEN_USER_COUNT = 8  # 同一用户指定时间步长内访问次数超过该值将屏蔽该用户
