# Generated by Django 5.1.1 on 2024-09-26 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='top',
            field=models.BooleanField(default=False, verbose_name='是否置顶'),
        ),
    ]
