# Generated by Django 5.1.1 on 2024-09-29 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_top'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='word_count',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='img',
            field=models.ImageField(blank=True, default='', upload_to='images/', verbose_name='图片'),
        ),
    ]
